AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Exclude:
    - 'spec/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
